### ISSUE TITLE
Fails on OSX

### ISSUE THREAD

**Issue by octplane** [anordal/reljump.fish#1]
~ $ jump src
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/stat.1.html

**Comment by anordal** [comment]
Thanks for the report!

I propose this change:

``` diff
@@ -49,7 +49,7 @@ function jump
                        else
                                set dst $dst/$path
                        end
-                       if not set i (stat -c '%i' $dst)
+                       if not set i (stat -L $dst)
                                return 1
                        end
                end
```

I see that I've used a Linux specific stat option. The option can be removed (its effect is to print less output, which I'm discarding anyway). The purpose of the command is to fail if the bookmark destination doesn't exist, and if so give me a hopefully localized error message for free.

I also see that adding the `-L` option would be a bonus fix (would detect if the bookmark destination is a broken symlink)

Maybe you could help me test that error behaviour:

```
begin
    set -xl LANG sv_SE.UTF-8
    stat -L ''
    or echo 'Failed successfully'
end
```

**Comment by octplane** [comment]
Not very impressive: 

```
~ $ begin
            set -xl LANG sv_SE.UTF-8
            stat -L ''
            or echo 'Failed successfully'
    end
stat: : stat: No such file or directory
Failed successfully
~  $ begin
            set -xl LANG fr_FR.UTF-8
            stat -L ''
            or echo 'Failed successfully'
    end
stat: : stat: No such file or directory
Failed successfully
```

Not sure the locale selection works very well... Apart from that, it is not complaining.
And your patch works, too.

**Comment by anordal** [comment]
Oh well, the _localized error message for free_ tactic is a bit optimistic, and maybe `stat` is not the best localized command. The alternative is to replace it with `test` plus some English.

Merci beaucoup !
