### ISSUE TITLE
Add autocomplete feature to jump

### ISSUE THREAD

**Issue by octplane** [anordal/reljump.fish#2]
I found this which can be probably be reused in some ways.

https://github.com/oh-my-fish/plugin-jump/blob/master/completions/jump.fish

My attempt at adding the completion resulted in adding :

```
            complete -c jump -e
            complete -c jump -f -a "command ls $markpath"
```

At the end of `set`. Which is working but unsatisfactory. It handles only the pure set bookmarks, will explode on scm bookmarks and is not properly initialized at fish startup.

Nevertheless, it provides a good starting point IMHO...

**Comment by anordal** [comment]
Yes this is an important missing feature. I think you're on to something, this basically works for me:

```
complete -c jump -f -a '(cd $HOME/.config/marks/; for i in *; echo $i; end)'
```

Problems:
- it doesn't filter out irrelevant bookmarks depending on $PWD
- that hardcoded path.

Not sure where you mean by the end of set, but I'm thinking to add the proper functionality as an (undocumented) option to jump itself, similar to `jump --ls`.

**Comment by anordal** [comment]
I made a branch for now: https://github.com/anordal/reljump.fish/tree/completion. Will rebase it, so let's continue discussing here.

**Comment by anordal** [comment]
The branch now has completion of bookmarks that works with multiple arguments, so that previous arguments properly influence which bookmarks are suggested.

I'm pretty satisfied with that, but I also want it to suggest ordinary paths when they start with ./
