### ISSUE TITLE
Completion is broken on OSX

### ISSUE THREAD

**Issue by octplane** [anordal/reljump.fish#3]
`jump usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]Apr 15 10:15:56 2016
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
`

When pressing TAB :sad:

**Comment by anordal** [comment]
Ouch, I see that I've used a GNU specific grep option (`-P` for perl compatible regex):
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/grep.1.html

I see that OS X has the _extended_ regex `-E`, which is just as good in this case:

``` diff
--- a/completions/jump.fish
+++ b/completions/jump.fish
@@ -31,10 +31,10 @@ function __fish_jump_suggest
        test $pre = .
        and set pre

-       set dejavu (stat . | grep -Pi '(device|inode)')
+       set dejavu (stat . | grep -Ei '(device|inode)')
        for i in $candidates
                set -l path (jump -p $pre/ $i ^/dev/null)
-               and set -l pathstat (stat -L $path | grep -Pi '(device|inode)')
+               and set -l pathstat (stat -L $path | grep -Ei '(device|inode)')
                and test "$pathstat" != "$dejavu"
                and printf '%s\n' $i
        end
```

Thanks for reporting this, Pierre!
